__imports__ = [ "base", "l2-inits/via.init.env" ]

[via_btc_watch]
confirmations_for_btc_msg = 3
btc_node_poll_interval = 1000
rpc_url = "http://0.0.0.0:18443"
rpc_user = "rpcuser"
rpc_password = "rpcpassword"
network = "regtest"
bootstrap_txids = []
actor_role = "Sequencer"

[via_btc_sender]
poll_interval = 1000
private_key = "cVZduZu265sWeAqFYygoDEE1FZ7wV9rpW5qdqjRkUehjaUMWLT1R"
max_aggregated_blocks_to_commit = 1
max_aggregated_proofs_to_commit = 1
max_txs_in_flight = 1
rpc_url = "http://0.0.0.0:18443"
rpc_user = "rpcuser"
rpc_password = "rpcpassword"
network = "regtest"
actor_role = "Sequencer"
da_identifier = "da_identifier_celestia"

[via_celestia_client]
api_node_url = "ws://localhost:26658"
auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiLCJhZG1pbiJdfQ.ut1X4u9XG5cbV0yaRAKfGp9xWVrz3NoEPGGRch13dFU"
blob_size_limit = 1973786

[rust]
log = """\
warn,\
zksync_node_framework=info,\
zksync_node_consensus=info,\
zksync_consensus_bft=info,\
zksync_consensus_network=info,\
zksync_consensus_storage=info,\
zksync_commitment_generator=info,\
zksync_core=debug,\
zksync_dal=info,\
zksync_db_connection=info,\
zksync_health_check=debug,\
zksync_eth_client=info,\
zksync_state_keeper=info,\
zksync_node_sync=info,\
zksync_storage=info,\
zksync_metadata_calculator=info,\
zksync_merkle_tree=info,\
zksync_node_api_server=info,\
zksync_node_db_pruner=info,\
zksync_reorg_detector=info,\
zksync_consistency_checker=info,\
zksync_state=debug,\
zksync_utils=debug,\
zksync_types=info,\
zksync_web3_decl=debug,\
loadnext=info,\
vm=info,\
zksync_external_node=info,\
zksync_snapshots_applier=debug,\
via_btc_watch=debug,\
via_state_keeper=debug,\
via_btc_sender=debug,\
via_da_dispatcher=debug,\
"""
