[object_store]
mode="FileBacked"
file_backed_base_path="artifacts"

[public_object_store]
mode="FileBacked"
file_backed_base_path="artifacts"

[prover_object_store]
mode="FileBacked"
file_backed_base_path="artifacts"

[snapshots_object_store]
mode="FileBacked"
file_backed_base_path="artifacts"

[snapshots_creator]
object_store={mode="FileBacked", file_backed_base_path="artifacts"}
