[via_btc_client]
# 'btc_rpc_user' is defined in the `via_private.toml`
# 'btc_rpc_password' is defined in the `via_private.toml`

# Name of the used Bitcoin network
network = "regtest"
# The Bitcoin RPC URL.
rpc_url = "http://0.0.0.0:18443"
# External fee APIs
external_apis = ["https://mempool.space/testnet/api/v1/fees/recommended"]
# Fee strategies
fee_strategies = ["fastestFee"]
# Use RPC to get the fee rate
use_rpc_for_fee_rate = true