[package]
name = "via_block_reverter_cli"
description = "Utility to revert blocks"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
zksync_config = { workspace = true, features = ["observability_ext"] }
zksync_env_config.workspace = true
zksync_core_leftovers.workspace = true
zksync_dal.workspace = true
zksync_protobuf_config.workspace = true
zksync_object_store.workspace = true
zksync_types.workspace = true
zksync_vlog.workspace = true
via_block_reverter.workspace = true

anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
